
server:
  port: 8080
  servlet:
    context-path: /api



feature-toggle:
#  storage: jdbc
  features:
    foo: false
    bar: true
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, info, feature-toggle



