
server:
  port: 8090
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/feature_toggle?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

feature-toggle:
  storage: jdbc

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, info, feature-toggle, feature-toggle-mgt




