CREATE TABLE TOGGLE_FEATURES
(
  ID int PRIMARY KEY AUTO_INCREMENT COMMENT 'primary id',
  FEATURE varchar(50) NOT NULL COMMENT 'unique feature name',
  FEATURE_VALUE varchar(20) DEFAULT 'FALSE' COMMENT 'feature switch value'
);
CREATE UNIQUE INDEX TOGGLE_FEATURES_id_uindex ON TOGGLE_FEATURES (ID);
CREATE UNIQUE INDEX TOGGLE_FEATURES_FEATURE_uindex ON TOGGLE_FEATURES (FEATURE);
ALTER TABLE TOGGLE_FEATURES COMMENT = 'feature toggle switch';